### ISSUE TITLE
Create README.md 

### ISSUE THREAD

**Issue by rohansx** [open-xyz/openxyz#10]
Create README.md for this repository accordingly

**Comment by giri-madhan** [comment]
Hi @rohansx , Could you assign this task to me? I have already created an PR for it here. https://github.com/open-xyz/openxyz/pull/11

Please let me know if any change is required. Thank you.

**Comment by rohansx** [comment]
@giri-madhan Thank you for your contribution. Would love if you join our organization and contribute to further projects.
I have sent you the invite link

**Comment by giri-madhan** [comment]
Thank you for the invite! I accepted it just now. Looking forward to contribute in whatever way I can.
