### ISSUE TITLE
Justify the content

### ISSUE THREAD

**Issue by rohansx** [open-xyz/openxyz#17]
![Screenshot from 2023-04-29 00-26-05](https://user-images.githubusercontent.com/33249782/235230623-0cc989ce-4ff1-44d0-b621-0c998f1032b9.png)

- Properly align the content from both the sides

**Comment by rossieeissor** [comment]
Please assign if you are looking for results like this:
![image](https://user-images.githubusercontent.com/99268704/235278984-9ad02c1b-cbf1-4706-88d0-ff831987a7cb.png)
