### ISSUE TITLE
Change the color of text

### ISSUE THREAD

**Issue by rohansx** [open-xyz/openxyz#6]
![Screenshot from 2023-04-27 02-03-20](https://user-images.githubusercontent.com/33249782/234697050-3b53ee32-825f-4d1b-bcae-7df89935dc64.png)

- Change the color of languages and database
- When we click on technology, database text-color changes to blue which looks like hyperlink 
- So change the color accordindly

**Comment by Sky-De** [comment]
Assign this to me
I will fix it

**Comment by rossieeissor** [comment]
How can I be assigned?

**Comment by Sky-De** [comment]
"Change the color of languages and database"
to what ?
which color do you prefer ?

**Comment by rohansx** [comment]
@Sky-De Change it to some standard color.
Make it white on black bg.
Feel free to suggesf if you have better suggestions
