### ISSUE TITLE
Change the color of footer

### ISSUE THREAD

**Issue by rohansx** [open-xyz/openxyz#7]
![Screenshot from 2023-04-27 02-14-52](https://user-images.githubusercontent.com/33249782/234698209-969c8e2b-7232-4db0-b00b-307eced9ec22.png)

- Change the bg color of footer to black and text-color to smoke white

**Comment by Sky-De** [comment]
Assign this to me 
I will fix

**Comment by rohansx** [comment]
@Sky-De all yours

**Comment by rohansx** [comment]
@Sky-De Thank you for your contribution. Also, would love if you join our organization and contribute to further projects.
I have sent you the invite link.

**Comment by Sky-De** [comment]
your welcome, you can close those issues now,
and i didn't get any invite which you mentioned

**Comment by rohansx** [comment]
@Sky-De I have invited you please check it
